# Generated by Django 4.0.6 on 2024-05-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
