# Generated by Django 4.0.6 on 2024-05-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hblog', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
